package Chapter4;

public class Lesson4_2_4 {
}

/*Выберите правильный ответ
Рассмотрим пример кода:


try {
    // код, бросающий исключения
} catch (RuntimeException e) {
    // ...
} catch (Exception e) {
    // ...
} catch (Error e) {
    // ...
} finally {
    // ...
}


Предположим, что во время исполнения программы в теле блока try было выброшено исключение типа java.lang.IllegalStateException.
Какие блоки catch-finally будут выполнены?
catch (Error e)
catch (Exception e)
>>>catch (RuntimeException e)
>>>finally*/
